# .goreleaser.yml
version: 2  # Specify the config version
project_name: backhaul
builds:
  - id: backhaul
    main: ./main.go 
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -ldflags=-s -w 
    env:
       - CGO_ENABLED=0


archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"


release:
   github:
    owner: Musixal
    name: backhaul
checksum:
  name_template: "checksums.txt"
changelog:
  use: git